### PR TITLE
add startle gifs to general.py

### PR DESCRIPTION
**Pull request by divyanshu887**
solved issue(#25 )

### CODE REVIEW

**Comment by starlightknown** [comment]
Could you add gifs from giphy online? The gifs from other site are not visible

**Comment by divyanshu887** [comment]
> Could you add gifs from giphy online? The gifs from other site are not visible

i have added this time only from giphy

**Comment by starlightknown** [comment]
Thank you so much for contributing!

**Comment by starlightknown** [comment]
@all-contributors please add @divyanshu887 for videos

**Comment by starlightknown** [comment]
@all-contributors please add @divyanshu887 for video

**Pull request merged**
